services:
  - type: web
    name: automated-trading-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FOREX_DATA_SERVICE_URL
        value: https://forex-data-service.onrender.com
      - key: TRADING_BOT_URL
        value: https://trading-signal-bot.onrender.com
