services:
  - type: web
    name: forex-data-service
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements-minimal.txt
    startCommand: gunicorn --workers 2 --bind 0.0.0.0:$PORT server:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
