services:
  - type: web
    name: binance-api-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5010
      - key: BINANCE_API_KEY
        value: 1XKI7cToJLgy0mS2Z22XHNJUWPhxVgtZRphNjzmo2v1pvAhUGMf0PB38BebCWQG4
      - key: BINANCE_SECRET_KEY
        value: sph6gyREZINWtUBk6rmIpQXT5h4tfu7sVf28yUUi8qwV8CBUHBr1W81B38hsJL85
