import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, Calendar, Clock, Share2, Facebook, Twitter, Linkedin } from 'lucide-react';

const BlogPost: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();

  const blogPosts = {
    'how-to-pass-any-prop-firm-challenge-in-30-days': {
      title: "How to Pass Any Prop Firm Challenge in 30 Days",
      category: "Strategy",
      readTime: "8 min read",
      publishDate: "Dec 28, 2024",
      excerpt: "Learn the 3-step framework used by our top funded traders: Conservative risk, fixed RR ratios, and the power of AI-assisted entries.",
      icon: "🎯",
      gradient: "from-blue-500 to-cyan-500",
      content: `
        <h2>The Ultimate 30-Day Prop Firm Challenge Strategy</h2>
        <p>After analyzing thousands of prop firm challenge attempts, we've identified the exact framework that turns 70% failure rates into 94% success rates.</p>

        <h3>Phase 1: Foundation (Days 1-10)</h3>
        <p>Focus on building unbreakable habits. Start with micro lots (0.01-0.05) and maintain a 1:2 risk-reward ratio. The goal isn't profits yet—it's consistency.</p>

        <h3>Phase 2: Scaling (Days 11-20)</h3>
        <p>Gradually increase position sizes while maintaining your risk parameters. Use our AI signals to identify high-probability setups.</p>

        <h3>Phase 3: Optimization (Days 21-30)</h3>
        <p>Fine-tune your approach based on the first 20 days. Focus on your strongest timeframes and avoid emotional trading.</p>

        <h3>Key Success Metrics:</h3>
        <ul>
          <li>Maintain drawdown under 3% at all times</li>
          <li>Achieve 65%+ win rate</li>
          <li>Keep average RR ratio above 1:1.5</li>
          <li>Trade during your most profitable hours</li>
        </ul>

        <p>Remember: Prop firm challenges test discipline more than skill. Our AI handles the complex analysis—you focus on execution.</p>
      `
    },
    'the-math-of-drawdown-why-most-traders-fail': {
      title: "The Math of Drawdown: Why Most Traders Fail",
      category: "Education",
      readTime: "6 min read",
      publishDate: "Dec 27, 2024",
      excerpt: "Losing 10% requires an 11% gain to recover, but losing 50% requires 100%. Discover how our Risk Guard prevents the 'Death Spiral.'",
      icon: "📊",
      gradient: "from-red-500 to-orange-500",
      content: `
        <h2>The Deadly Mathematics of Trading Losses</h2>
        <p>Most traders don't understand how devastating drawdowns can be. Let's break down the cold, hard math that destroys 90% of trading accounts.</p>

        <h3>The Recovery Nightmare</h3>
        <p>Here's what it takes to recover from common drawdown levels:</p>
        <ul>
          <li><strong>10% loss</strong> requires 11.1% gain to break even</li>
          <li><strong>20% loss</strong> requires 25% gain to break even</li>
          <li><strong>30% loss</strong> requires 42.9% gain to break even</li>
          <li><strong>50% loss</strong> requires 100% gain to break even</li>
        </ul>

        <h3>The Death Spiral</h3>
        <p>Most traders make this mistake: after a losing streak, they increase position sizes to "make up" for losses. This creates a dangerous cycle where one bad trade wipes out days of profits.</p>

        <h3>How Risk Guard Protects You</h3>
        <p>Our automated risk management:</p>
        <ul>
          <li>Sets hard daily drawdown limits (3-5%)</li>
          <li>Automatically reduces position sizes after losses</li>
          <li>Implements breakeven stops on winning trades</li>
          <li>Prevents emotional position sizing increases</li>
        </ul>

        <p>The math doesn't lie. Protect your capital with automation, not emotion.</p>
      `
    },
    'ai-vs-human-emotion-the-2026-trading-outlook': {
      title: "AI vs. Human Emotion: The 2026 Trading Outlook",
      category: "Future",
      readTime: "10 min read",
      publishDate: "Dec 26, 2024",
      excerpt: "In a market dominated by algorithms, manual trading is becoming a disadvantage. See how Nexus AI levels the playing field for retail traders.",
      icon: "🤖",
      gradient: "from-purple-500 to-pink-500",
      content: `
        <h2>The Algorithmic Revolution in Trading</h2>
        <p>By 2026, 80% of market volume will be generated by algorithms. Human traders are at a severe disadvantage unless they leverage AI technology.</p>

        <h3>The Speed Advantage</h3>
        <p>AI processes market data 1000x faster than humans:</p>
        <ul>
          <li><strong>Human reaction time:</strong> 200-500 milliseconds</li>
          <li><strong>AI processing time:</strong> 0.001 milliseconds</li>
          <li><strong>Market execution:</strong> Sub-millisecond</li>
        </ul>

        <h3>Emotion-Free Decision Making</h3>
        <p>Humans suffer from cognitive biases that destroy returns:</p>
        <ul>
          <li><strong>Fear of missing out (FOMO)</strong> - Chasing markets</li>
          <li><strong>Loss aversion</strong> - Holding losing positions</li>
          <li><strong>Confirmation bias</strong> - Ignoring contradictory data</li>
          <li><strong>Overconfidence</strong> - Taking excessive risks</li>
        </ul>

        <h3>How Nexus AI Levels the Playing Field</h3>
        <p>Our AI provides retail traders with institutional-grade tools:</p>
        <ul>
          <li>Real-time multi-factor analysis across 50+ indicators</li>
          <li>Probability-weighted entry and exit signals</li>
          <li>Automated risk management and position sizing</li>
          <li>24/7 market monitoring and execution</li>
        </ul>

        <h3>The Future is Automated</h3>
        <p>Successful traders in 2026 will be those who use AI as their competitive advantage. Manual trading is becoming a hobby, not a profession.</p>

        <p>Join the algorithmic revolution. Your competition already has.</p>
      `
    }
  };

  const post = slug ? blogPosts[slug as keyof typeof blogPosts] : null;

  if (!post) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-white mb-4">Blog Post Not Found</h1>
          <button
            onClick={() => navigate('/')}
            className="text-cyan-400 hover:text-cyan-300 transition-colors"
          >
            ← Back to Home
          </button>
        </div>
      </div>
    );
  }

  const shareUrl = window.location.href;
  const shareTitle = post.title;

  const handleShare = (platform: string) => {
    const urls = {
      twitter: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareTitle)}&url=${encodeURIComponent(shareUrl)}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`
    };

    window.open(urls[platform as keyof typeof urls], '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="min-h-screen bg-gray-900">
      {/* Header */}
      <div className="bg-gradient-to-br from-gray-800 to-gray-900 border-b border-gray-700">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <button
            onClick={() => navigate('/')}
            className="flex items-center text-cyan-400 hover:text-cyan-300 transition-colors mb-6"
          >
            <ArrowLeft className="w-5 h-5 mr-2" />
            Back to Home
          </button>

          <div className="flex items-center space-x-4 mb-6">
            <div className={`w-16 h-16 rounded-xl bg-gradient-to-r ${post.gradient} flex items-center justify-center text-2xl`}>
              {post.icon}
            </div>
            <div>
              <span className={`inline-block px-3 py-1 rounded-full text-xs font-semibold bg-gradient-to-r ${post.gradient} text-white mb-2`}>
                {post.category}
              </span>
              <div className="flex items-center space-x-4 text-sm text-gray-400">
                <div className="flex items-center">
                  <Calendar className="w-4 h-4 mr-1" />
                  {post.publishDate}
                </div>
                <div className="flex items-center">
                  <Clock className="w-4 h-4 mr-1" />
                  {post.readTime}
                </div>
              </div>
            </div>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold text-white mb-6 leading-tight">
            {post.title}
          </h1>

          <p className="text-xl text-gray-300 mb-8">
            {post.excerpt}
          </p>

          {/* Share Buttons */}
          <div className="flex items-center space-x-4">
            <span className="text-gray-400 font-medium">Share:</span>
            <button
              onClick={() => handleShare('twitter')}
              className="flex items-center space-x-2 bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg transition-colors"
            >
              <Twitter className="w-4 h-4" />
              <span>Twitter</span>
            </button>
            <button
              onClick={() => handleShare('facebook')}
              className="flex items-center space-x-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors"
            >
              <Facebook className="w-4 h-4" />
              <span>Facebook</span>
            </button>
            <button
              onClick={() => handleShare('linkedin')}
              className="flex items-center space-x-2 bg-blue-700 hover:bg-blue-800 text-white px-4 py-2 rounded-lg transition-colors"
            >
              <Linkedin className="w-4 h-4" />
              <span>LinkedIn</span>
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="prose prose-invert prose-lg max-w-none"
        >
          <div
            dangerouslySetInnerHTML={{ __html: post.content }}
            style={{
              color: '#e5e7eb',
              lineHeight: '1.8',
            }}
          />

          {/* CTA Section */}
          <div className="mt-16 p-8 bg-gradient-to-r from-purple-500/10 to-blue-500/10 border border-purple-500/20 rounded-2xl">
            <h3 className="text-2xl font-bold text-white mb-4">Ready to Start Your Trading Journey?</h3>
            <p className="text-gray-300 mb-6">
              Join thousands of traders who have transformed their trading with AI-powered tools and strategies.
            </p>
            <button
              onClick={() => navigate('/signup')}
              className="bg-gradient-to-r from-purple-500 to-blue-500 text-white font-semibold py-3 px-8 rounded-lg hover:from-purple-600 hover:to-blue-600 transition-all duration-300 transform hover:scale-105"
            >
              Start Free Trial
            </button>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default BlogPost;
