import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Calendar, Clock, ArrowRight, TrendingUp, Target, Brain, X } from 'lucide-react';

const TradersEdgeBlog: React.FC = () => {
  const navigate = useNavigate();
  const [selectedPost, setSelectedPost] = useState<any>(null);

  const blogPosts = [
    {
      title: "How to Pass Any Prop Firm Challenge in 30 Days",
      excerpt: "Learn the 3-step framework used by our top funded traders: Conservative risk, fixed RR ratios, and the power of AI-assisted entries.",
      category: "Strategy",
      readTime: "8 min read",
      publishDate: "Dec 28, 2024",
      icon: Target,
      gradient: "from-blue-500 to-cyan-500",
      fullContent: `
        <h2>The Ultimate 30-Day Prop Firm Challenge Strategy</h2>
        <p>After analyzing thousands of prop firm challenge attempts, we've identified the exact framework that turns 70% failure rates into 94% success rates.</p>

        <h3>Phase 1: Foundation (Days 1-10)</h3>
        <p>Focus on building unbreakable habits. Start with micro lots (0.01-0.05) and maintain a 1:2 risk-reward ratio. The goal isn't profits yet—it's consistency.</p>

        <h3>Phase 2: Scaling (Days 11-20)</h3>
        <p>Gradually increase position sizes while maintaining your risk parameters. Use our AI signals to identify high-probability setups.</p>

        <h3>Phase 3: Optimization (Days 21-30)</h3>
        <p>Fine-tune your approach based on the first 20 days. Focus on your strongest timeframes and avoid emotional trading.</p>

        <h3>Key Success Metrics:</h3>
        <ul>
          <li>Maintain drawdown under 3% at all times</li>
          <li>Achieve 65%+ win rate</li>
          <li>Keep average RR ratio above 1:1.5</li>
          <li>Trade during your most profitable hours</li>
        </ul>

        <p>Remember: Prop firm challenges test discipline more than skill. Our AI handles the complex analysis—you focus on execution.</p>
      `
    },
    {
      title: "The Math of Drawdown: Why Most Traders Fail",
      excerpt: "Losing 10% requires an 11% gain to recover, but losing 50% requires 100%. Discover how our Risk Guard prevents the 'Death Spiral.'",
      category: "Education",
      readTime: "6 min read",
      publishDate: "Dec 27, 2024",
      icon: TrendingUp,
      gradient: "from-red-500 to-orange-500",
      fullContent: `
        <h2>The Deadly Mathematics of Trading Losses</h2>
        <p>Most traders don't understand how devastating drawdowns can be. Let's break down the cold, hard math that destroys 90% of trading accounts.</p>

        <h3>The Recovery Nightmare</h3>
        <p>Here's what it takes to recover from common drawdown levels:</p>
        <ul>
          <li><strong>10% loss</strong> requires 11.1% gain to break even</li>
          <li><strong>20% loss</strong> requires 25% gain to break even</li>
          <li><strong>30% loss</strong> requires 42.9% gain to break even</li>
          <li><strong>50% loss</strong> requires 100% gain to break even</li>
        </ul>

        <h3>The Death Spiral</h3>
        <p>Most traders make this mistake: after a losing streak, they increase position sizes to "make up" for losses. This creates a dangerous cycle where one bad trade wipes out days of profits.</p>

        <h3>How Risk Guard Protects You</h3>
        <p>Our automated risk management:</p>
        <ul>
          <li>Sets hard daily drawdown limits (3-5%)</li>
          <li>Automatically reduces position sizes after losses</li>
          <li>Implements breakeven stops on winning trades</li>
          <li>Prevents emotional position sizing increases</li>
        </ul>

        <p>The math doesn't lie. Protect your capital with automation, not emotion.</p>
      `
    },
    {
      title: "AI vs. Human Emotion: The 2026 Trading Outlook",
      excerpt: "In a market dominated by algorithms, manual trading is becoming a disadvantage. See how Nexus AI levels the playing field for retail traders.",
      category: "Future",
      readTime: "10 min read",
      publishDate: "Dec 26, 2024",
      icon: Brain,
      gradient: "from-purple-500 to-pink-500",
      fullContent: `
        <h2>The Algorithmic Revolution in Trading</h2>
        <p>By 2026, 80% of market volume will be generated by algorithms. Human traders are at a severe disadvantage unless they leverage AI technology.</p>

        <h3>The Speed Advantage</h3>
        <p>AI processes market data 1000x faster than humans:</p>
        <ul>
          <li><strong>Human reaction time:</strong> 200-500 milliseconds</li>
          <li><strong>AI processing time:</strong> 0.001 milliseconds</li>
          <li><strong>Market execution:</strong> Sub-millisecond</li>
        </ul>

        <h3>Emotion-Free Decision Making</h3>
        <p>Humans suffer from cognitive biases that destroy returns:</p>
        <ul>
          <li><strong>Fear of missing out (FOMO)</strong> - Chasing markets</li>
          <li><strong>Loss aversion</strong> - Holding losing positions</li>
          <li><strong>Confirmation bias</strong> - Ignoring contradictory data</li>
          <li><strong>Overconfidence</strong> - Taking excessive risks</li>
        </ul>

        <h3>How Nexus AI Levels the Playing Field</h3>
        <p>Our AI provides retail traders with institutional-grade tools:</p>
        <ul>
          <li>Real-time multi-factor analysis across 50+ indicators</li>
          <li>Probability-weighted entry and exit signals</li>
          <li>Automated risk management and position sizing</li>
          <li>24/7 market monitoring and execution</li>
        </ul>

        <h3>The Future is Automated</h3>
        <p>Successful traders in 2026 will be those who use AI as their competitive advantage. Manual trading is becoming a hobby, not a profession.</p>

        <p>Join the algorithmic revolution. Your competition already has.</p>
      `
    }
  ];

  const handleReadMore = (post: any) => {
    // Navigate to internal blog post page
    const slugMap: Record<string, string> = {
      "How to Pass Any Prop Firm Challenge in 30 Days": "how-to-pass-any-prop-firm-challenge-in-30-days",
      "The Math of Drawdown: Why Most Traders Fail": "the-math-of-drawdown-why-most-traders-fail",
      "AI vs. Human Emotion: The 2026 Trading Outlook": "ai-vs-human-emotion-the-2026-trading-outlook"
    };

    const slug = slugMap[post.title as string];
    if (slug) {
      navigate(`/blog/${slug}`);
    }
  };

  const closeModal = () => {
    setSelectedPost(null);
  };

  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 relative z-10 overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0 bg-gradient-to-br from-pink-500/[0.02] via-transparent to-cyan-500/[0.02]" />

      <div className="max-w-7xl mx-auto relative z-10">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-6xl font-bold mb-6 tracking-tight">
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-white to-white/70">
              The Trader's{" "}
            </span>
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-pink-300 to-cyan-300">
              Edge
            </span>
          </h2>
          <p className="text-xl text-white/40 max-w-3xl mx-auto font-light">
            Expert insights, proven strategies, and the latest in AI-powered trading technology
          </p>
        </div>

        {/* Blog Posts Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {blogPosts.map((post, index) => (
            <motion.article
              key={post.title}
              className="group bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 border border-gray-700 hover:border-gray-600 transition-all duration-300 hover:transform hover:scale-105 cursor-pointer"
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
            >
              {/* Category Badge */}
              <div className="flex items-center justify-between mb-6">
                <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-gradient-to-r ${post.gradient} text-white`}>
                  {post.category}
                </span>
                <div className="flex items-center text-gray-400 text-sm">
                  <Clock className="w-4 h-4 mr-1" />
                  {post.readTime}
                </div>
              </div>

              {/* Icon */}
              <div className={`inline-flex items-center justify-center w-12 h-12 rounded-xl bg-gradient-to-r ${post.gradient} mb-6 group-hover:scale-110 transition-transform duration-300`}>
                <post.icon className="w-6 h-6 text-white" />
              </div>

              {/* Title */}
              <h3 className="text-xl font-bold text-white mb-4 leading-tight group-hover:text-gray-200 transition-colors duration-300">
                {post.title}
              </h3>

              {/* Excerpt */}
              <p className="text-gray-400 mb-6 leading-relaxed">
                {post.excerpt}
              </p>

              {/* Footer */}
              <div className="flex items-center justify-between">
                <div className="flex items-center text-gray-500 text-sm">
                  <Calendar className="w-4 h-4 mr-1" />
                  {post.publishDate}
                </div>
                <button
                  onClick={() => handleReadMore(post)}
                  className="flex items-center text-cyan-400 font-medium group-hover:text-cyan-300 transition-colors duration-300 hover:scale-105 transform"
                >
                  Read More
                  <ArrowRight className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform duration-300" />
                </button>
              </div>
            </motion.article>
          ))}
        </div>

        {/* CTA Section */}
        <motion.div
          className="text-center mt-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          viewport={{ once: true }}
        >
          <div className="bg-gradient-to-r from-gray-900 to-gray-800 rounded-2xl p-8 border border-gray-700">
            <h3 className="text-2xl font-bold text-white mb-4">
              Stay Ahead of the Market
            </h3>
            <p className="text-gray-400 mb-6 max-w-2xl mx-auto">
              Get weekly insights on AI trading, prop firm strategies, and market analysis delivered to your inbox.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center max-w-md mx-auto">
              <input
                type="email"
                placeholder="Enter your email"
                className="flex-1 px-4 py-3 bg-gray-800 border border-gray-600 rounded-lg text-white placeholder-gray-400 focus:ring-2 focus:ring-cyan-500 focus:border-transparent"
              />
              <button className="px-6 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-lg hover:from-cyan-600 hover:to-blue-600 transition-all duration-300 transform hover:scale-105">
                Subscribe
              </button>
            </div>
            <p className="text-xs text-gray-500 mt-4">
              Join 15,000+ traders. Unsubscribe anytime.
            </p>
          </div>
        </motion.div>
      </div>

      {/* Blog Post Modal */}
      {selectedPost && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-gray-900 border border-gray-700 rounded-2xl max-w-4xl w-full max-h-[85vh] overflow-hidden">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-6 border-b border-gray-700">
              <div className="flex items-center space-x-4">
                <div className={`w-12 h-12 rounded-xl bg-gradient-to-r ${selectedPost.gradient} flex items-center justify-center`}>
                  <selectedPost.icon className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white">{selectedPost.title}</h3>
                  <div className="flex items-center space-x-4 text-sm text-gray-400">
                    <span className={`px-2 py-1 rounded-full text-xs bg-gradient-to-r ${selectedPost.gradient} text-white`}>
                      {selectedPost.category}
                    </span>
                    <span>{selectedPost.readTime}</span>
                    <span>{selectedPost.publishDate}</span>
                  </div>
                </div>
              </div>
              <button
                onClick={closeModal}
                className="text-gray-400 hover:text-white transition-colors"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
              <div
                className="prose prose-invert max-w-none"
                dangerouslySetInnerHTML={{ __html: selectedPost.fullContent }}
                style={{
                  color: '#e5e7eb',
                  lineHeight: '1.7',
                }}
              />
            </div>

            {/* Modal Footer */}
            <div className="flex items-center justify-between p-6 border-t border-gray-700">
              <div className="flex items-center space-x-4">
                <button className="text-cyan-400 hover:text-cyan-300 transition-colors">
                  ← Previous Post
                </button>
                <button className="text-cyan-400 hover:text-cyan-300 transition-colors">
                  Next Post →
                </button>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-gray-400">Share:</span>
                <button className="text-gray-400 hover:text-white transition-colors">📘</button>
                <button className="text-gray-400 hover:text-white transition-colors">🐦</button>
                <button className="text-gray-400 hover:text-white transition-colors">💼</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};

export default TradersEdgeBlog;
